/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiHelperRouteImport } from './routes/ai-helper'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BuildRouteImport } from './routes/build'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CustomRouteImport } from './routes/custom'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as GalleryAdminRouteImport } from './routes/gallery-admin'
import { Route as JoinRouteImport } from './routes/join'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SkinsRouteImport } from './routes/skins'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiHelperRoute = AiHelperRouteImport.update({
  id: '/ai-helper',
  path: '/ai-helper',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRoute = CustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryAdminRoute = GalleryAdminRouteImport.update({
  id: '/gallery-admin',
  path: '/gallery-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SkinsRoute = SkinsRouteImport.update({
  id: '/skins',
  path: '/skins',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => CheckoutRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-helper': typeof AiHelperRoute
  '/auth': typeof AuthRoute
  '/build': typeof BuildRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/custom': typeof CustomRoute
  '/editor': typeof EditorRoute
  '/gallery-admin': typeof GalleryAdminRoute
  '/join': typeof JoinRoute
  '/pricing': typeof PricingRoute
  '/skins': typeof SkinsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-helper': typeof AiHelperRoute
  '/auth': typeof AuthRoute
  '/build': typeof BuildRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/custom': typeof CustomRoute
  '/editor': typeof EditorRoute
  '/gallery-admin': typeof GalleryAdminRoute
  '/join': typeof JoinRoute
  '/pricing': typeof PricingRoute
  '/skins': typeof SkinsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-helper': typeof AiHelperRoute
  '/auth': typeof AuthRoute
  '/build': typeof BuildRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/custom': typeof CustomRoute
  '/editor': typeof EditorRoute
  '/gallery-admin': typeof GalleryAdminRoute
  '/join': typeof JoinRoute
  '/pricing': typeof PricingRoute
  '/skins': typeof SkinsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-helper'
    | '/auth'
    | '/build'
    | '/checkout'
    | '/custom'
    | '/editor'
    | '/gallery-admin'
    | '/join'
    | '/pricing'
    | '/skins'
    | '/checkout/return'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-helper'
    | '/auth'
    | '/build'
    | '/checkout'
    | '/custom'
    | '/editor'
    | '/gallery-admin'
    | '/join'
    | '/pricing'
    | '/skins'
    | '/checkout/return'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/ai-helper'
    | '/auth'
    | '/build'
    | '/checkout'
    | '/custom'
    | '/editor'
    | '/gallery-admin'
    | '/join'
    | '/pricing'
    | '/skins'
    | '/checkout/return'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiHelperRoute: typeof AiHelperRoute
  AuthRoute: typeof AuthRoute
  BuildRoute: typeof BuildRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  CustomRoute: typeof CustomRoute
  EditorRoute: typeof EditorRoute
  GalleryAdminRoute: typeof GalleryAdminRoute
  JoinRoute: typeof JoinRoute
  PricingRoute: typeof PricingRoute
  SkinsRoute: typeof SkinsRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-helper': {
      id: '/ai-helper'
      path: '/ai-helper'
      fullPath: '/ai-helper'
      preLoaderRoute: typeof AiHelperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom': {
      id: '/custom'
      path: '/custom'
      fullPath: '/custom'
      preLoaderRoute: typeof CustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery-admin': {
      id: '/gallery-admin'
      path: '/gallery-admin'
      fullPath: '/gallery-admin'
      preLoaderRoute: typeof GalleryAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skins': {
      id: '/skins'
      path: '/skins'
      fullPath: '/skins'
      preLoaderRoute: typeof SkinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutReturnRoute: typeof CheckoutReturnRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutReturnRoute: CheckoutReturnRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiHelperRoute: AiHelperRoute,
  AuthRoute: AuthRoute,
  BuildRoute: BuildRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  CustomRoute: CustomRoute,
  EditorRoute: EditorRoute,
  GalleryAdminRoute: GalleryAdminRoute,
  JoinRoute: JoinRoute,
  PricingRoute: PricingRoute,
  SkinsRoute: SkinsRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
